const Realestate = [
  {
    id: 1,
    image: "images/houses1.jpg",
    price: 1000,
    name: "Palm Harbour",
    location: "New York",
    type: "Houses",
  },
  {
    id: 2,
    image: "images/houses2.jpg",
    price: 6000,
    name: "Palm Harbour",
    location: "Toranto",
    type: "Houses",
  },
  {
    id: 3,
    image: "images/flats1.jpg",
    price: 3000,
    name: "Palm Harbour",
    location: "New York",
    type: "Flats",
  },
  {
    id: 4,
    image: "images/houses1.jpg",
    price: 3000,
    name: "SunShine",
    location: "India",
    type: "Houses",
  },
  {
    id: 5,
    image: "images/villas1.jpg",
    price: 1000,
    name: "Palm Harbour",
    location: "New York",
    type: "Villas",
  },
  {
    id: 6,
    image: "images/houses2.jpg",
    price: 6000,
    name: "Palm Harbour",
    location: "New York",
    type: "Houses",
  },
  {
    id: 7,
    image: "images/houses1.jpg",
    price: 6000,
    name: "Palm Harbour",
    location: "New York",
    type: "Houses",
  },
  {
    id: 8,
    image: "images/houses2.jpg",
    price: 3000,
    name: "Palm Harbour",
    location: "New York",
    type: "Houses",
  },
  {
    id: 9,
    image: "images/flats2.jpg",
    price: 1000,
    name: "Palm Harbour",
    location: "New York",
    type: "Flats",
  },
  {
    id: 10,
    image: "images/houses1.jpg",
    price: 3000,
    name: "Palm Harbour",
    location: "Vegas",
    type: "Houses",
  },
  {
    id: 11,
    image: "images/villas3.jpg",
    price: 1000,
    name: "Palm Harbour",
    location: "New York",
    type: "Villas",
  },
  {
    id: 12,
    image: "images/flats1.jpg",
    price: 6000,
    name: "Palm Harbour",
    location: "New York",
    type: "Flats",
  },
  {
    id: 13,
    image: "images/villas4.jpg",
    price: 1000,
    name: "Palm Harbour",
    location: "New York",
    type: "Villas",
  },
];

export default Realestate;
